document.writeln("<nav class=\'navbar navbar-expand-lg\'>");
document.writeln("        <div class=\'container-fluid\'>");
document.writeln("            <a class=\'navbar-brand\' href=\'https://www.youtube.com/watch?v=o6wtDPVkKqI\'><h2><strong>新世紀福音戰士</strong></h2></a>");
document.writeln("            <button class=\'navbar-toggler\' type=\'button\' data-bs-toggle=\'collapse\' data-bs-target=\'#navbarNavDropdown\' aria-controls=\'navbarNavDropdown\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("            <span class=\'navbar-toggler-icon\'></span>");
document.writeln("            </button>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'navbarNavDropdown\'>");
document.writeln("                <ul class=\'navbar-nav\'>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link active\' aria-current=\'page\' href=\'../index.html\'>首頁</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\' href=\'../song/song.html\'>主題曲</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item dropdown\'>");
document.writeln("                        <a class=\'nav-link dropdown-toggle\' href=\'#\' role=\'button\' data-bs-toggle=\'dropdown\' aria-expanded=\'false\'>");
document.writeln("                            劇情介紹");
document.writeln("                        </a>");
document.writeln("                        <ul class=\'dropdown-menu \'>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\' href=\'../movie/tv.html\'>TV版</a></li>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\' href=\'../movie/movie1.html\'>劇場版：序</a></li>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\' href=\'../movie/movie2.html\'>劇場版：破</a></li>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\' href=\'../movie/movie3.html\'>劇場版：Q</a></li>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\' href=\'../movie/movie4.html\'>劇場版：終</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item dropdown\'>");
document.writeln("                        <a class=\'nav-link dropdown-toggle\' href=\'#\' role=\'button\' data-bs-toggle=\'dropdown\' aria-expanded=\'false\'>");
document.writeln("                            人物介紹");
document.writeln("                        </a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\' href=\'../character/shinji.html\'>碇真嗣</a></li>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\'  href=\'../character/rei.html\'>綾波零</a></li>");
document.writeln("                            <li><a class=\'dropdown-item dropdown\' href=\'../character/asuka.html\'>惣流&middot;明日香&middot;蘭格雷</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'nav-item\'>");
document.writeln("                        <a class=\'nav-link\' href=\'../cold_know/cold_knowledge.html\'>冷知識</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");